baseURL = "https://kutty.netlify.app"
title = "Kutty"

languageCode = "en-us"
DefaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Praveen Juge"
  sitename = "Kutty"
  image = "/brand/og.png"
  description = "Kutty is a tailwind plugin for building web applications. It has a set of accessible and reusable components that are commonly used in web applications."

[taxonomies]
  category = "categories"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false